"""
Build ITEMS_NEEDING_ICONS.md — a focused tracking file listing every item
that still needs an icon assignment.

An item "needs an icon" when:
  - resolve_pack_ref() returns "" (no valid art-pack or recolor reference)
  - AND icon_path does NOT contain "Assets/Icons/Items/" (custom hand-drawn)

Items with valid pack refs or custom hand-drawn icons are already assigned
and are excluded.

Output: Docs/ITEMS_NEEDING_ICONS.md

Usage:
    python DevTools/build_needs_icons.py
"""

import os
import sys
import json

# Add DevTools to path so we can import the resolver
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from generate_items_html_data import resolve_pack_ref, get_region

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ITEMS_DIR = os.path.join(BASE, "Data", "Items", "Templates")
OUTPUT = os.path.join(BASE, "Docs", "ITEMS_NEEDING_ICONS.md")

REGION_LABELS = {
    "base": "BASE / STARTER",
    "region_1": "REGION 1 — THORNHAVEN",
    "region_2": "REGION 2 — FUNGAL MARSHES",
    "region_3": "REGION 3 — SUNKEN SHOALS",
    "region_4": "REGION 4 — ASHEN HORIZONS",
    "region_5": "REGION 5 — STARFALL EXPANSE",
    "region_6": "REGION 6 — NECROPOLIS CRYPTS",
    "region_7": "REGION 7 — FRACTURED REALM",
}

REGION_ORDER = [
    "base", "region_1", "region_2", "region_3", "region_4",
    "region_5", "region_6", "region_7",
]

# Display order for categories
CAT_ORDER = {
    "equipment": 0,
    "material": 1,
    "consumable": 2,
    "book": 3,
    "tool": 4,
    "backpack": 5,
    "other": 9,
}

CAT_LABELS = {
    "equipment": "Equipment",
    "material": "Materials",
    "consumable": "Consumables",
    "book": "Class Books",
    "tool": "Tools",
    "backpack": "Bags",
}


def classify_item(data, tags):
    """Classify an item into a display category."""
    item_type = data.get("item_type", "")
    if "book" in tags:
        return "book"
    if item_type in ("weapon", "armor", "offhand", "accessory"):
        return "equipment"
    if item_type == "bag" or item_type == "backpack":
        return "backpack"
    if item_type == "material":
        return "material"
    if item_type == "consumable":
        return "consumable"
    if item_type == "tool":
        return "tool"
    return item_type or "other"


def load_items_needing_icons():
    """Load all item templates and return only those needing icon assignments."""
    needing = []

    for fname in sorted(os.listdir(ITEMS_DIR)):
        if not fname.endswith(".json"):
            continue
        path = os.path.join(ITEMS_DIR, fname)
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        item_id = data.get("id", fname.replace(".json", ""))
        icon_path = data.get("icon_path", "")
        pack_ref = resolve_pack_ref(icon_path, item_id)

        # Skip items that already have icon assignments
        if pack_ref:
            continue  # Has a valid pack ref (art pack or recolor)
        if "Assets/Icons/Items/" in icon_path:
            continue  # Has a custom hand-drawn icon

        # This item needs an icon
        tags = data.get("tags", [])
        region = get_region(tags)
        cat = classify_item(data, tags)
        tier = data.get("tier", 1) or 1
        item_type = data.get("item_type", "")
        display_name = data.get("display_name", item_id)
        icon_hint = data.get("icon_hint", "")

        needing.append({
            "id": item_id,
            "name": display_name,
            "region": region,
            "cat": cat,
            "tier": tier,
            "item_type": item_type,
            "icon_path": icon_path,
            "icon_hint": icon_hint,
        })

    return needing


def main():
    items = load_items_needing_icons()
    total_needing = len(items)

    # Group by region
    by_region = {}
    for it in items:
        by_region.setdefault(it["region"], []).append(it)

    # Sort within each region: category order, then tier, then name
    for region_items in by_region.values():
        region_items.sort(key=lambda x: (
            CAT_ORDER.get(x["cat"], 9), x["tier"], x["name"]
        ))

    # Build output
    lines = []
    lines.append("# Items Needing Icons")
    lines.append("")
    lines.append(f"**{total_needing} items** need icon assignments.")
    lines.append("")
    lines.append("Auto-generated by `DevTools/build_needs_icons.py` — regenerate anytime.")
    lines.append("")

    for region in REGION_ORDER:
        region_items = by_region.get(region, [])
        if not region_items:
            continue

        label = REGION_LABELS.get(region, region.upper())
        lines.append(f"## {label} ({len(region_items)} items)")
        lines.append("")

        current_cat = None
        current_tier = None

        for it in region_items:
            # Category header
            if it["cat"] != current_cat:
                # Add blank separator before new category (except the first)
                if current_cat is not None:
                    lines.append("")
                current_cat = it["cat"]
                current_tier = None
                cat_label = CAT_LABELS.get(it["cat"], it["cat"].title())
                lines.append(f"### {cat_label}")
                lines.append("")

            # For equipment, show tier sub-headers
            if it["cat"] == "equipment" and it["tier"] != current_tier:
                # Blank line before tier header (except the first tier in a category)
                if current_tier is not None:
                    lines.append("")
                current_tier = it["tier"]
                tier_count = sum(
                    1 for x in region_items
                    if x["cat"] == "equipment" and x["tier"] == it["tier"]
                )
                lines.append(f"**T{it['tier']} ({tier_count})**")
                lines.append("")

            # Item line
            if it["cat"] == "equipment":
                lines.append(f"- [ ] {it['name']} (`{it['id']}`) — {it['item_type']}")
            else:
                lines.append(f"- [ ] {it['name']} (`{it['id']}`)")

        lines.append("")

    # Ensure file ends with newline
    output_text = "\n".join(lines)
    if not output_text.endswith("\n"):
        output_text += "\n"

    # Write output
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(output_text)

    print(f"Written: {OUTPUT}")
    print(f"  {total_needing} items need icon assignments")

    # Per-region breakdown
    for region in REGION_ORDER:
        count = len(by_region.get(region, []))
        if count:
            label = REGION_LABELS.get(region, region)
            print(f"  {label}: {count}")


if __name__ == "__main__":
    main()
