"""
Build the ITEM_ICON_LEDGER.md from all Data/Items/Templates/*.json.
Shows every item with its pack_ref code (e.g. G#20) so you never have
to look through individual JSON files to find icon assignments.

Output: Docs/ITEM_ICON_LEDGER.md

Recolored items show an asterisk: G#20* means the source is G#20 but
the actual icon is a recolored copy in Items_Recolored/.

Usage:
    python DevTools/build_icon_ledger.py
"""

import os
import sys

# Add DevTools to path so we can import the resolver
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from generate_items_html_data import resolve_pack_ref, get_region

import json
import re

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ITEMS_DIR = os.path.join(BASE, "Data", "Items", "Templates")
OUTPUT = os.path.join(BASE, "Docs", "ITEM_ICON_LEDGER.md")


def load_all_items():
    """Load all item templates and resolve pack refs."""
    items = []
    for fname in sorted(os.listdir(ITEMS_DIR)):
        if not fname.endswith(".json"):
            continue
        path = os.path.join(ITEMS_DIR, fname)
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        item_id = data.get("id", fname.replace(".json", ""))
        tags = data.get("tags", [])
        region = get_region(tags)
        icon_path = data.get("icon_path", "")
        pack_ref = resolve_pack_ref(icon_path, item_id)
        display_name = data.get("display_name", item_id)
        item_type = data.get("item_type", "")
        tier = data.get("tier", 1) or 1

        # Classify: equipment, material, consumable, etc.
        if "book" in tags:
            cat = "book"
        elif item_type in ("weapon", "armor", "offhand", "accessory", "bag"):
            cat = "equipment"
        elif item_type == "material":
            cat = "material"
        elif item_type == "consumable":
            cat = "consumable"
        elif item_type == "tool":
            cat = "tool"
        elif item_type == "backpack":
            cat = "backpack"
        else:
            cat = item_type or "other"

        items.append({
            "id": item_id,
            "name": display_name,
            "region": region,
            "cat": cat,
            "tier": tier,
            "icon_path": icon_path,
            "ref": pack_ref,
        })

    return items


REGION_LABELS = {
    "base": "BASE / STARTER",
    "region_1": "REGION 1 — THORNHAVEN",
    "region_2": "REGION 2 — FUNGAL MARSHES",
    "region_3": "REGION 3 — SUNKEN SHOALS",
    "region_4": "REGION 4 — ASHEN HORIZONS",
    "region_5": "REGION 5 — STARFALL EXPANSE",
    "region_6": "REGION 6 — NECROPOLIS CRYPTS",
    "region_7": "REGION 7 — FRACTURED REALM",
}

REGION_ORDER = ["base", "region_1", "region_2", "region_3", "region_4",
                "region_5", "region_6", "region_7"]


def main():
    items = load_all_items()

    # Group by region
    by_region = {}
    for it in items:
        by_region.setdefault(it["region"], []).append(it)

    # Sort within each region: cat order, then tier, then name
    cat_order = {"consumable": 0, "equipment": 1, "backpack": 2,
                 "material": 3, "book": 4, "tool": 5, "other": 9}
    for region_items in by_region.values():
        region_items.sort(key=lambda x: (
            cat_order.get(x["cat"], 9), x["tier"], x["name"]
        ))

    # Stats
    total = len(items)
    with_ref = sum(1 for it in items if it["ref"])
    without_icon = sum(1 for it in items if not it["icon_path"])

    lines = []
    lines.append("# Item Icon Ledger")
    lines.append("")
    lines.append(f"**{total} items** | **{with_ref} with pack refs** | **{without_icon} missing icons**")
    lines.append("")
    lines.append("Pack ref format: `CODE#NUM` (e.g. `G#20` = Helmets Icon20.png)")
    lines.append("Asterisk `*` = recolored copy (source is the listed pack ref)")
    lines.append("")
    lines.append("Auto-generated by `DevTools/build_icon_ledger.py` — do not edit by hand.")
    lines.append("")

    for region in REGION_ORDER:
        region_items = by_region.get(region, [])
        if not region_items:
            continue

        label = REGION_LABELS.get(region, region)
        lines.append(f"## {label} ({len(region_items)} items)")
        lines.append("")

        current_cat = None
        current_tier = None
        for it in region_items:
            # Category header
            cat_label = {
                "consumable": "Consumables", "equipment": "Equipment",
                "backpack": "Bags", "material": "Materials",
                "book": "Class Books", "tool": "Tools",
            }.get(it["cat"], it["cat"].title())

            if it["cat"] != current_cat:
                current_cat = it["cat"]
                current_tier = None
                lines.append(f"### {cat_label}")
                lines.append("")

            # Tier sub-header for equipment
            if it["cat"] in ("equipment", "backpack") and it["tier"] != current_tier:
                current_tier = it["tier"]
                tier_items = [x for x in region_items
                              if x["cat"] == it["cat"] and x["tier"] == it["tier"]]
                lines.append(f"**T{it['tier']} ({len(tier_items)})**")
                lines.append("")

            # Item line
            ref_str = it["ref"] if it["ref"] else "—"
            tier_str = f" T{it['tier']}" if it["cat"] in ("equipment", "backpack") else ""
            lines.append(f"- {it['name']}{tier_str} — `{ref_str}`")

        lines.append("")

    # Write output
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Written: {OUTPUT}")
    print(f"  {total} items, {with_ref} with pack refs, {without_icon} missing icons")


if __name__ == "__main__":
    main()
